// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymgjgvjpmkwglaykyain.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZ2pndmpwbWt3Z2xheWt5YWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDg4NDcsImV4cCI6MjA2ODc4NDg0N30.Ln7_whmqY_8yYk7nbSrzlUtgwkqKbf3S5eAxvV7IcI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});